### ISSUE TITLE
Allow an admin to create delegations

### ISSUE THREAD

**Issue by cahana** [UniversityOfHawaii/sad-html#31]
A user with the admin role must be able to create a delegation for anyone.

**Comment by shaun-blake** [comment]
@cahana - Do we also need to make an admin page where they can see, update, and delete the delegations for another user?  If not, once they created the delegation for the other person, they won't be able to see do anything with it again.

**Comment by cahana** [comment]
Yes, we would need a page like that to see, update and delete delegations for another user.
